# Generated by Django 5.1.3 on 2024-12-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_teacher_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
